env_name: StackRGBTestTripletActorDict-v0
num_processes: 128
no_cuda: False
algo: a2c
plr: 7.0e-4
vlr: 7.0e-4
alpha: 0.99
gamma: 0.99
eps: 1.0e-5
use_gae: True
gae_lambda: 0.95
entropy_coef: 0.01
value_loss_coef: null
max_grad_norm: 0.5
seed: 1
cuda_deterministic: False
num_steps: 256
log_interval: 10
save_interval: 100
num_env_steps: 1.0e+8
log_dir: '/tmp/gym/'
save_dir: './trained_models/'
use_proper_time_limits: False
eval_interval: null
use_linear_lr_decay: True

model:
  rec_type: lstm

  feature_extract:
    embed_out: 256
    vision_out: 256
    flatten_out: 256
    hidden_size: 256
    mlp_dim: 3
    post: attn
    act_fn: relu
    heads: 4
    embed_dim: 256
    layer_norm: True
    post_layer_norm: True

  policy_keys: &1 ['blue:pos_relative_to_pinch+pose',
                   'green:pos_relative_to_pinch+pose',
                   'red:pos_relative_to_pinch+pose',
                   'robot0:gripper',
                   'robot0:joint0',
                   'robot0:joint1',
                   'robot0:joint2',
                   'robot0:joint3',
                   'robot0:joint4',
                   'robot0:joint5',
                   'robot0:joint6',
                   'robot0:pinch',
                   'robot0:wrist']

  value_keys: *1

