env_name: StackRGBTestTriplet-v0

num_envs_per_cpu: 72
num_learners: 1
use_multi_thread: True

device: infer
seed: 1
log_interval: 10
save_interval: 100
num_env_steps: 1.0e+8
log_dir: '/tmp/gym/'
save_dir: './benchmark_model_flat/TestTriplet1'
eval_interval: null

plr: 5.0e-4
vlr: 5.0e-4
alpha: 0.99
gamma: 0.99
eps: 1.0e-5
max_grad_norm: 0.5

gae_lambda: 0.95
entropy_coef: 0.01
num_mini_batch: 4
ppo_epoch: 4
num_steps: 10

model:
  hidden_size: 512

  feature_extract:
    vision_out: 512
    flatten_out: 512
    act_fn: relu