env_name: StackRGBTrain-v1

num_envs_per_cpu: 4
num_learners: 1
use_multi_thread: False

device: cpu
seed: 1
log_interval: 100
save_interval: 100
num_env_steps: 1.0e+7
log_dir: '/tmp/gym/'
save_dir: './benchmark_model/'
eval_interval: null

plr: 7.0e-4
vlr: 7.0e-4
alpha: 0.99
gamma: 0.99
eps: 1.0e-5
max_grad_norm: 0.5

gae_lambda: 0.95
entropy_coef: 0.01
num_mini_batch: 1
ppo_epoch: 3
num_steps: 10

model:
  hidden_size: 512

  feature_extract:
    vision_out: 512
    flatten_out: 512
    act_fn: relu